# Generated by Django 2.0.1 on 2019-06-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190604_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=500),
        ),
    ]
