# Generated by Django 2.0.1 on 2019-06-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190604_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='バカです', max_length=500),
        ),
        migrations.AlterField(
            model_name='choice',
            name='name',
            field=models.CharField(default='テスト', max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_title',
            field=models.CharField(default='誰ですか？', max_length=50),
        ),
    ]
