# Generated by Django 2.0.1 on 2019-06-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190605_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
