# Generated by Django 2.0.1 on 2019-06-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20190605_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
