# Generated by Django 2.0.1 on 2019-06-05 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20190605_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
