# Generated by Django 2.0.1 on 2019-06-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20190605_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
